<template>
    <div class="space-y-4">
        <div class="space-y-2 border-b border-slate-600">
            <h1 class="text-3xl font-medium">Fabian Torres</h1>
            <p class="text-lg font-light text-gray-400">Full Stack Developer</p>
            <p class="text-wrap font-mono text-lg font-light text-gray-300">
                I build simple but effective, front and back end solutions
            </p>
            <div class="flex flex-row space-x-2 pb-4">
                <IconLink size="2rem" name="uil:github"
                            redirect="https://github.com/lumix103" 
                            hoverColor="rgb(14 165 233 / var(--tw-bg-opacity))" />
                <IconLink size="2rem" name="uil:linkedin" 
                            redirect="https://github.com/lumix103" 
                            hoverColor="rgb(14 165 233 / var(--tw-bg-opacity))" />
                <IconLink size="2rem" name="uil:envelope" 
                            redirect="mailto:fabiant@protonmail.com" 
                            hoverColor="rgb(14 165 233 / var(--tw-bg-opacity))" />
            </div>
        </div>

        <div class="space-y-2 border-b border-slate-600">
            <h2 class="text-2xl font-medium">About Me</h2>
            <p class="pb-4 font-mono text-gray-300">
                My humble beginings started in 2013, learning Visual Basic, making silly
                scripts and programs, in the computer lab. Now, I am full fledged web
                developer. Dewelving my hands in technologies such as:
                <span class="font-bold text-gray-50">Go, Python, TypeScript, React, and Vue.</span>
                Although, I do have my niche interest in compilers.
            </p>
        </div>

        <div class="space-y-2 border-b border-slate-600">
            <h2 class="text-2xl font-medium">Expereince</h2>
            <ul class="space-y-4 pb-4">
                <li>
                    <ExperienceCard company="Funded Bull" from="May 2024" to="Present"
                        title="Junior Full Stack Developer"
                        desc="Build and maintain critical components of Funded Bull's back and front end. 
                                    Also, closely worked with multiple team members to craft a responsive and rich exchange platform."
                        :keywords="['React', 'Remix', 'TypeScript', 'Tailwind CSS']" />
                </li>
                <li>
                    <ExperienceCard company="Data Annotation" from="February 2024" to="May 2024" title="AI Trainer"
                        desc="Conducted thorough evaluations of code generated by AI models, ensuring correctness and optimal performance to meet user expectations and maintain the chatbot’s reliability."
                        :keywords="['C/C++', 'Python', 'JavaScript']" />
                </li>
                <li>
                    <ExperienceCard company="Data Mine Network" from="August 2022" to="December 2023"
                        title="Data Science Mentee"
                        desc="Utilized advanced data analysis tools, including Python, R, Awk, NumPy, and Matplotlib, to analyze and interpret complex datasets."
                        :keywords="['Awk', 'Python', 'R', 'NumPy', 'Pandas', 'Matplotlib']" />
                </li>
            </ul>
        </div>

        
    </div>
</template>
