<template>
  <div class="container mx-auto space-y-4">
    <div class="space-y-2 border-b border-mirage-600">
      <h1 class="text-3xl font-medium">Fabian Torres</h1>
      <p class="text-lg font-light text-silver-300">Full Stack Developer</p>
      <p class="text-wrap font-mono text-lg font-light text-silver-200">
        I build simple but effective, front and back end solutions.
      </p>
      <div class="flex flex-row space-x-2 pb-4">
        <IconLink
          size="2rem"
          name="uil:github"
          redirect="https://github.com/lumix103"
          hoverColor="rgb(242 214 214 / var(--tw-text-opacity))"
        />
        <IconLink
          size="2rem"
          name="uil:linkedin"
          redirect="https://github.com/lumix103"
          hoverColor="rgb(242 214 214 / var(--tw-text-opacity))"
        />
        <IconLink
          size="2rem"
          name="uil:envelope"
          redirect="mailto:fabiant@protonmail.com"
          hoverColor="rgb(242 214 214 / var(--tw-text-opacity))"
        />
      </div>
    </div>

    <div class="space-y-2 border-b border-mirage-600">
      <h2 class="text-2xl font-medium">About Me</h2>
      <p class="pb-4 font-mono text-silver-200">
        My humble beginings started in 2013, learning Visual Basic, making silly
        scripts and programs, in the computer lab. Now, I am full fledged web
        developer. Dewelving my hands in technologies such as:
        <span class="font-bold text-silver-50"
          >Go, Python, TypeScript, React, and Vue.</span
        >
        Although, I do have my niche interest in compilers.
      </p>
    </div>

    <div class="space-y-2 border-b border-mirage-600">
      <h2 class="text-2xl font-medium">Expereince</h2>
      <ul class="space-y-4 pb-4">
        <li>
          <ExperienceCard
            company="Funded Bull"
            from="May 2024"
            to="Present"
            title="Junior Full Stack Developer"
            desc="Build and maintain critical components of Funded Bull's back and front end. 
                                    Also, closely worked with multiple team members to craft a responsive and rich exchange platform."
            :keywords="['React', 'Remix', 'TypeScript', 'Tailwind CSS']"
          />
        </li>
        <li>
          <ExperienceCard
            company="Data Annotation"
            from="February 2024"
            to="May 2024"
            title="AI Trainer"
            desc="Conducted thorough evaluations of code generated by AI models, ensuring correctness and optimal performance to meet user expectations and maintain the chatbot’s reliability."
            :keywords="['C/C++', 'Python', 'JavaScript']"
          />
        </li>
        <li>
          <ExperienceCard
            company="Data Mine Network"
            from="August 2022"
            to="December 2023"
            title="Data Science Mentee"
            desc="Utilized advanced data analysis tools, including Python, R, Awk, NumPy, and Matplotlib, to analyze and interpret complex datasets."
            :keywords="['Awk', 'Python', 'R', 'NumPy', 'Pandas', 'Matplotlib']"
          />
        </li>
      </ul>
    </div>

    <div class="space-y-2 border-b border-mirage-600">
      <h2 class="text-2xl font-medium">Projects</h2>
      <p class="font-mono text-lg font-light text-silver-200">
        If you would like to see more of my projects, my
        <a
          href="https://github.com/lumix103"
          class="group inline-flex flex-row items-center text-manilla-200 underline hover:text-blossom-200"
        >
          GitHub
          <Icon
            size="1rem"
            name="uil:arrow-up-right"
            class="transition ease-in-out group-hover:-translate-y-1"
          />
        </a>
        is just a click away.
      </p>
      <ul class="space-y-4 pb-4">
        <li>
          <ProjectCard
            project="fabiantorres.me"
            from="June 2024"
            to="Present"
            title="Static Site"
            desc="A static website built with Nuxt, to display my experience and projects."
            redirect="https://github.com/lumix103/lumix103.github.io"
            ,
            :keywords="['Nuxt', 'Vue', 'Tailwind CSS']"
          />
        </li>
        <li>
          <ProjectCard
            project="MedConnect"
            from="October 2023"
            to="December 2023"
            title="Medical Dashboard"
            desc="A medical dashboard, built on Go, Mux, and HTML. The dashboard seperates users by patient and clients, and allows both users to edit and set appointments."
            redirect="https://github.com/lumix103/cse-4050-project"
            ,
            :keywords="['Go', 'HTML', 'CSS']"
          />
        </li>
        <li>
          <ProjectCard
            project="Elemental Quest"
            from="January 2023"
            to="May 2023"
            title="Unity Game"
            desc="A 2D puzzle platformer, built in a colabrative effort utilizing Agile Developement."
            redirect="https://github.com/lumix103/Elemental-Quest"
            ,
            :keywords="['C#', 'Unity']"
          />
        </li>
        <li>
          <ProjectCard
            project="D-Bot"
            from="January 2022"
            to="May 2022"
            title="Bot Dashboard"
            desc="A Dashboard made Next.JS, and other framework technologies to host, edit, and monitor a Discord bot application. This project was made in a large team using a Kaban style approach."
            redirect="https://github.com/ThomasCross257/DBot-Backend"
            ,
            :keywords="['Node.JS', 'Express.JS', 'Next.JS', 'Discord API']"
          />
        </li>
        <li>
          <ProjectCard
            project="BrainF**k"
            from="October 2021"
            to="October 2021"
            title="Interpreter"
            desc="A Python interpreter, designed to read and execute BrainF**k code."
            redirect="https://github.com/lumix103/cse-4050-project"
            ,
            :keywords="['Python']"
          />
        </li>
        <li>
          <ProjectCard
            project="Soup Kitchen"
            from="Feburary 2019"
            to="October 2019"
            title="Discord Bot"
            desc="A personalized Discord Bot built for the needs of my server."
            redirect="https://github.com/lumix103/PyBrainFuck"
            ,
            :keywords="['Node.JS', 'JavaScript', 'Discord API']"
          />
        </li>
      </ul>
    </div>
  </div>
</template>
